# Scratch code to "factor" table names into some sort of matrix.
#
# table IDs are always 6 long, unless:
#   racial or puerto rican subclass
#   a handful of imputation tables
# 
# more cleanup: field names, inconsistent with colons such as 
# potential table filters:
#   'in puerto rico' (de facto all ending in 'PR')
#   'in united states' (opposite of above, but also five more tables whose names indicate 'IN THE UNITED STATES')
#   'technical tables': 2 unweighted counts; 10 quality measures; 97 imputations
#   racial breakdowns

import re
from collections import defaultdict
import csv

def load_rows():
    table_data = defaultdict(dict)
    r = csv.reader(open("acs2011_1yr_Sequence_Number_and_Table_Number_Lookup.csv"))
    headers = r.next()
    for row in r:
        if not row[3]:
            title = row[7]
            if title.startswith('Universe'):
                junk,uni = title.split(':',1)
                table_data[row[1]]['universe'] = uni.strip()
            else:
                table_data[row[1]]['title'] = title
    return [(k,v['title'],v['universe']) for k,v in table_data.items()]
        
SUBTABLE_STRINGS = [ 
 '(AMERICAN INDIAN AND ALASKA NATIVE  ALONE)',# stupid double white space!
 '(AMERICAN INDIAN AND ALASKA NATIVE ALONE HOUSEHOLDER)',
 '(AMERICAN INDIAN AND ALASKA NATIVE ALONE)',
 '(ASIAN ALONE HOUSEHOLDER)',
 '(ASIAN ALONE)',
 '(BLACK OR AFRICAN AMERICAN ALONE HOUSEHOLDER)',
 '(BLACK OR AFRICAN AMERICAN ALONE)',
 '(NATIVE HAWAIIAN AND OTHER PACIFIC ISLANDER ALONE HOUSEHOLDER)',
 '(NATIVE HAWAIIAN AND OTHER PACIFIC ISLANDER ALONE)',
 '(SOME OTHER RACE ALONE HOUSEHOLDER)',
 '(SOME OTHER RACE ALONE)',
 '(WHITE ALONE HOUSEHOLDER)',
 '(WHITE ALONE)',
 '(WHITE ALONE, NOT HISPANIC OR LATINO HOUSEHOLDER)',
 '(WHITE ALONE, NOT HISPANIC OR LATINO)',
]

def build_subtable_map(rows):
    """
    outlier: a PR table with no corresponding US table (relates to B06010/B06010PR) only seems to omit income levels for foreign born. can we just skip this one?
    ('C06010PR',
      'PLACE OF BIRTH BY INDIVIDUAL INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS) IN PUERTO RICO',
      'Population 15 years and over in Puerto Rico')
    """
    SUBTABLE_PATTERN = re.compile('^(\w+\d+)(\w+)$')
    smap = defaultdict(dict)
    for x in rows:
        table_id = x[0]
        if table_id[-1].isalpha():
            base_table_id, code = SUBTABLE_PATTERN.match(table_id).groups()
            smap[base_table_id][code] = x
    for x in rows: # there seem to be 18 out of 111 'subtable groups' which don't have a 'root'
        if x[0] in smap:
            smap[x[0]]['root'] = x
    return smap
    
def prune_subtables(rows):
    """Partition off all table codes which end in alphabetic (racial subgroup or puerto rico) and any tables which are 'parents' to those."""
    rows = list(rows)
    smap = build_subtable_map(rows)
    for v in smap.values():
        for tup in v.values():
            rows.remove(tup)
    return rows, smap
    
    
def prune_technical(rows):
    rows = list(rows)
    tech = [x for x in rows if x[0][1:3] in ['00','98','99']]
    for x in tech:
        rows.remove(x)
    return rows, tech
    
def megapruned(rows):
    rows, smap = prune_subtables(rows)
    rows, tech = prune_technical(rows)
    return rows,smap,tech
    
"""
Exactly 7 tables have the word 'FOR' more than once. 3 are imputation tables. The other 4:

[('B10010',
  'MEDIAN FAMILY INCOME FOR FAMILIES WITH GRANDPARENT HOUSEHOLDERS AND/OR SPOUSES LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS BY RESPONSIBILITY FOR OWN GRANDCHILDREN AND PRESENCE OF PARENT OF GRANDCHILDREN',
  'amilies with grandparent householders and/or spouses living with grandchildren'),
 ('B10050',
  'GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS BY RESPONSIBILITY FOR OWN GRANDCHILDREN BY LENGTH OF TIME RESPONSIBLE FOR OWN GRANDCHILDREN FOR THE POPULATION 30 YEARS AND OVER',
  'Population 30 years and over'),
 ('B15010',
  "DETAILED FIELD OF BACHELOR'S DEGREE FOR FIRST MAJOR FOR THE POPULATION 25 YEARS AND OVER",
  "POPULATION 25 YEARS AND OVER WITH A BACHELOR'S DEGREE OR HIGHER ATTAINMENT"),
 ('B15011',
  "SEX BY AGE BY FIELD OF BACHELOR'S DEGREE FOR FIRST MAJOR FOR THE POPULATION 25 YEARS AND OVER",
  "POPULATION 25 YEARS AND OVER WITH A BACHELOR'S DEGREE OR HIGHER ATTAINMENT")]

"""    
def build_table_dict(row):
    d = { 'table_id': row[0], 'original_name': row[1], 'universe': row[2], 'components': [] }
    name = row[1]
    parts = name.rsplit(' FOR ',1) # see above; sometimes 'FOR' appears more than once
    if len(parts) == 2:
        d['universe_from_name'] = parts[1]
        name = parts[0]
    for component in name.split(' BY '):
        d['components'].extend(component.split(' AND '))
    
    return d
    
#323 components...
COMPONENTS = [
 'ABILITY TO SPEAK ENGLISH',
 'ABILITY TO SPEAK ENGLISH OF GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'AGE',
 'AGE OF GRANDCHILD',
 'AGE OF HOUSEHOLDER',
 'AGE OF OWN CHILDREN',
 'AGE OF OWN CHILDREN UNDER 18 YEARS',
 'AGE OF OWN CHILDREN UNDER 18 YEARS IN FAMILIES',
 'AGE OF RELATED CHILDREN',
 'AGE OF RELATED CHILDREN UNDER 18 YEARS',
 'AGGREGATE CONTRACT RENT (DOLLARS)',
 'AGGREGATE EARNINGS IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE FAMILY INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE GROSS RENT (DOLLARS)',
 'AGGREGATE HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE INCOME DEFICIT (DOLLARS) IN THE PAST 12 MONTHS',
 'AGGREGATE INCOME DEFICIT (DOLLARS) IN THE PAST 12 MONTHS OF UNRELATED INDIVIDUALS',
 'AGGREGATE INTEREST, DIVIDENDS, OR NET RENTAL INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE NONFAMILY HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE NUMBER OF ROOMS',
 'AGGREGATE NUMBER OF VEHICLES (CAR, TRUCK, OR VAN) USED IN COMMUTING',
 'AGGREGATE NUMBER OF VEHICLES AVAILABLE',
 'AGGREGATE OTHER TYPES OF INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE PRICE ASKED (DOLLARS)',
 'AGGREGATE PUBLIC ASSISTANCE INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE REAL ESTATE TAXES PAID (DOLLARS)',
 'AGGREGATE RENT ASKED (DOLLARS)',
 'AGGREGATE RETIREMENT INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE SELECTED MONTHLY OWNER COSTS (DOLLARS)',
 'AGGREGATE SELF-EMPLOYMENT INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE SOCIAL SECURITY INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE SUPPLEMENTAL SECURITY INCOME (SSI) IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'AGGREGATE TRAVEL TIME TO WORK (IN MINUTES) OF WORKERS',
 'AGGREGATE USUAL HOURS WORKED IN THE PAST 12 MONTHS',
 'AGGREGATE VALUE (DOLLARS)',
 'AGGREGATE WAGE OR SALARY INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'ALASKA NATIVE (AIAN) ALONE OR IN ANY COMBINATION',
 'ALASKA NATIVE ALONE',
 'ALASKA NATIVE ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES',
 'AMBULATORY DIFFICULTY',
 'AMERICAN INDIAN',
 'ANCESTRY',
 'ASIAN ALONE',
 'ASIAN ALONE OR IN ANY COMBINATION',
 'ASIAN ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES',
 'AVERAGE HOUSEHOLD SIZE OF OCCUPIED HOUSING UNITS',
 'BEDROOMS',
 'BLACK OR AFRICAN AMERICAN ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES',
 'CASH PUBLIC ASSISTANCE INCOME',
 'CITIZENSHIP STATUS',
 'CITIZENSHIP STATUS IN THE UNITED STATES',
 'CLASS OF WORKER',
 'CLASS OF WORKER ',
 'COGNITIVE DIFFICULTY',
 'COLLEGE OR GRADUATE SCHOOL ENROLLMENT',
 'CONTRACT RENT',
 'COUNTY LEVEL',
 "DETAILED FIELD OF BACHELOR'S DEGREE FOR FIRST MAJOR",
 'DETAILED OCCUPATION',
 'DETAILED RACE',
 'DIRECT-PURCHASE HEALTH INSURANCE',
 'DISABILITY STATUS',
 'DISABILITY STATUS OF GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'DIVORCES IN THE LAST YEAR',
 'EARNINGS IN THE PAST 12 MONTHS',
 'EARNINGS IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'EDUCATIONAL ATTAINMENT',
 'EDUCATIONAL ATTAINMENT OF HOUSEHOLDER',
 'EMPLOYER-BASED HEALTH INSURANCE ',
 'EMPLOYMENT STATUS',
 'EMPLOYMENT STATUS OF GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'EMPLOYMENT STATUS OF PARENTS',
 'FAMILIES',
 'FAMILY INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'FAMILY SIZE',
 'FAMILY TYPE',
 "FIELD OF BACHELOR'S DEGREE FOR FIRST MAJOR",
 'FINANCIAL CONDITIONS',
 'FIRST ANCESTRY REPORTED',
 'FULL-TIME WORK STATUS IN THE PAST 12 MONTHS',
 'GEOGRAPHICAL MOBILITY IN THE PAST YEAR',
 'GINI INDEX OF INCOME INEQUALITY',
 'GRANDCHILDREN UNDER 18 YEARS LIVING WITH A GRANDPARENT HOUSEHOLDER',
 'GRANDPARENT RESPONSIBILITY',
 'GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'GRANDPARENTS RESPONSIBLE',
 'GROSS RENT',
 'GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS',
 'GROUP QUARTERS POPULATION',
 'HEALTH INSURANCE COVERAGE STATUS',
 'HEARING DIFFICULTY',
 'HISPANIC OR LATINO ORIGIN',
 'HOUSE HEATING FUEL',
 'HOUSEHOLD INCOME',
 'HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'HOUSEHOLD INCOME QUINTILE UPPER LIMITS',
 'HOUSEHOLD LANGUAGE',
 'HOUSEHOLD SIZE',
 'HOUSEHOLD TYPE',
 'HOUSEHOLD TYPE (INCLUDING LIVING ALONE)',
 'HOUSEHOLDER STATUS',
 'HOUSEHOLDS',
 'HOUSEHOLDS IN WHICH NO ONE 14',
 'HOUSEHOLDS WITH GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS',
 'HOUSING UNITS',
 'INCLUSION OF UTILITIES IN RENT',
 'INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'INDEPENDENT LIVING DIFFICULTY',
 'INDUSTRY',
 'INTEREST, DIVIDENDS, OR NET RENTAL INCOME IN THE PAST 12 MONTHS',
 'KITCHEN FACILITIES',
 'LABOR FORCE PARTICIPATION',
 'LABOR FORCE STATUS',
 'LANGUAGE',
 'LANGUAGE SPOKEN AT HOME',
 'LANGUAGE SPOKEN AT HOME ABILITY TO SPEAK ENGLISH',
 'LENGTH OF TIME RESPONSIBLE FOR OWN GRANDCHILDREN',
 'LEVEL OF SCHOOL',
 'LIVING ALONE',
 'LIVING ARRANGEMENT',
 'LIVING ARRANGEMENTS',
 'LOWER CONTRACT RENT QUARTILE (DOLLARS)',
 'LOWER VALUE QUARTILE (DOLLARS)',
 'MARITAL STATUS',
 'MARRIAGES ENDING IN WIDOWHOOD IN THE LAST YEAR',
 'MARRIAGES IN THE LAST YEAR',
 'MEALS INCLUDED IN RENT',
 'MEAN HOUSEHOLD INCOME OF QUINTILES',
 'MEAN USUAL HOURS WORKED IN THE PAST 12 MONTHS',
 'MEANS OF TRANSPORTATION TO WORK',
 'MEDIAN AGE',
 'MEDIAN CONTRACT RENT (DOLLARS)',
 'MEDIAN DURATION OF CURRENT MARRIAGE IN YEARS',
 'MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'MEDIAN FAMILY INCOME FOR FAMILIES WITH GRANDPARENT HOUSEHOLDERS AND/OR SPOUSES LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'MEDIAN GROSS RENT',
 'MEDIAN GROSS RENT (DOLLARS)',
 'MEDIAN GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS (DOLLARS)',
 'MEDIAN HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'MEDIAN HOUSEHOLD INCOME THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'MEDIAN INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'MEDIAN MONTHLY HOUSING COSTS (DOLLARS)',
 'MEDIAN NONFAMILY HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'MEDIAN NUMBER OF ROOMS',
 'MEDIAN REAL ESTATE TAXES PAID (DOLLARS)',
 'MEDIAN SELECTED MONTHLY OWNER COSTS (DOLLARS)',
 'MEDIAN SELECTED MONTHLY OWNER COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS',
 'MEDIAN VALUE',
 'MEDIAN VALUE (DOLLARS)',
 'MEDIAN YEAR HOUSEHOLDER MOVED INTO UNIT',
 'MEDIAN YEAR STRUCTURE BUILT',
 'MEDICAID/MEANS-TESTED PUBLIC COVERAGE',
 'MEDICARE COVERAGE',
 'MONTHLY HOUSING COSTS',
 'MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS',
 'MORTGAGE STATUS',
 'MOVERS BETWEEN REGIONS IN THE UNITED STATES',
 'MULTIGENERATIONAL HOUSEHOLDS',
 'NATIVE HAWAIIAN',
 'NATIVITY',
 'NATIVITY IN THE UNITED STATES',
 'NATIVITY OF CHILDREN UNDER 18 YEARS IN FAMILIES',
 'NATIVITY OF OWN CHILDREN UNDER 18 YEARS IN FAMILIES',
 'NATIVITY OF PARENTS',
 'NONFAMILY HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)',
 'NONFAMILY HOUSEHOLDS',
 'NUMBER',
 'NUMBER OF DISABILITIES',
 'NUMBER OF EARNERS IN FAMILY',
 'NUMBER OF OWN CHILDREN UNDER 18 YEARS',
 'NUMBER OF PERSONS IN FAMILY',
 'NUMBER OF RELATED CHILDREN UNDER 18 YEARS',
 'NUMBER OF TIMES MARRIED',
 'NUMBER OF WORKERS IN FAMILY',
 'NUMBER OF WORKERS IN FAMILY IN THE PAST 12 MONTHS',
 'NUMBER OF WORKERS IN HOUSEHOLD',
 'OCCUPANCY STATUS',
 'OCCUPANTS PER ROOM',
 'OCCUPATION',
 'OTHER PACIFIC ISLANDER ALONE',
 'OTHER PACIFIC ISLANDER ALONE OR IN ANY COMBINATION',
 'OTHER PACIFIC ISLANDER ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES',
 'OTHER TYPES OF INCOME IN THE PAST 12 MONTHS',
 'OVER', ## from "AND OVER"? wouldn't want to split that
 'OVER SPEAKS ENGLISH ONLY OR SPEAKS A LANGUAGE OTHER THAN ENGLISH AT HOME', ## from "AND OVER"? wouldn't want to split that
 'OVER, HOUSEHOLD SIZE', ## from "AND OVER"? wouldn't want to split that
 'OWN CHILDREN UNDER 18 YEARS',
 'PEOPLE REPORTING ANCESTRY',
 'PEOPLE REPORTING MULTIPLE ANCESTRY',
 'PEOPLE REPORTING SINGLE ANCESTRY',
 'PERIOD OF MILITARY SERVICE',
 'PERIOD OF NATURALIZATION',
 'PLACE OF BIRTH',
 'PLACE OF WORK',
 'PLACE OF WORK--MINOR CIVIL DIVISION LEVEL',
 'PLACE OF WORK--PLACE LEVEL',
 'PLACE OF WORK--STATE',
 'PLUMBING FACILITIES',
 'POPULATION IN SUBFAMILIES',
 'POPULATION UNDER 18 YEARS',
 'POVERTY STATUS',
 'POVERTY STATUS IN THE PAST 12 MONTHS',
 'POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES',
 'POVERTY STATUS IN THE PAST 12 MONTHS OF GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'POVERTY STATUS IN THE PAST 12 MONTHS OF INDIVIDUALS',
 'POVERTY STATUS IN THE PAST 12 MONTHS OF RELATED CHILDREN UNDER 18 YEARS',
 'POVERTY STATUS IN THE PAST 12 MONTHS OF UNRELATED INDIVIDUALS 15 YEARS',
 'POVERTY STATUS OF INDIVIDUALS IN THE PAST 12 MONTHS',
 'PRESENCE',
 'PRESENCE OF CHILDREN UNDER 18 YEARS',
 'PRESENCE OF NONRELATIVES',
 'PRESENCE OF OWN CHILDREN',
 'PRESENCE OF OWN CHILDREN UNDER 18 YEARS',
 'PRESENCE OF OWN CHILDREN UNDER 18 YEARS IN MARRIED-COUPLE FAMILIES',
 'PRESENCE OF PARENT',
 'PRESENCE OF PEOPLE 60 YEARS',
 'PRESENCE OF PEOPLE 65 YEARS',
 'PRESENCE OF PEOPLE UNDER 18 YEARS',
 'PRESENCE OF RELATED CHILDREN UNDER 18 YEARS',
 'PRESENCE OF UNMARRIED PARTNER',
 'PRESENCE OF UNMARRIED PARTNER OF HOUSEHOLDER',
 'PRICE ASKED',
 'PRIVATE HEALTH INSURANCE',
 'PRIVATE HEALTH INSURANCE ',
 'PRIVATE HEALTH INSURANCE STATUS',
 'PUBLIC ASSISTANCE INCOME',
 'PUBLIC ASSISTANCE INCOME IN THE PAST 12 MONTHS',
 'PUBLIC ASSISTANCE INCOME OR FOOD STAMPS/SNAP IN THE PAST 12 MONTHS',
 'PUBLIC HEALTH INSURANCE',
 'PUBLIC HEALTH INSURANCE STATUS',
 'QUINTILE',
 'RACE',
 'RACE OF HOUSEHOLDER',
 'RATINGS',
 'RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS',
 'RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS OF FAMILIES',
 'RATIO OF INCOME TO POVERTY LEVEL OF FAMILIES IN THE PAST 12 MONTHS',
 'RATIO OF VALUE TO HOUSEHOLD INCOME IN THE PAST 12 MONTHS',
 'REAL ESTATE TAXES PAID',
 'RECEIPT OF FOOD STAMPS/SNAP IN THE PAST 12 MONTHS',
 'RECEIPT OF PUBLIC ASSISTANCE INCOME IN THE PAST 12 MONTHS',
 'RECEIPT OF SUPPLEMENTAL SECURITY INCOME (SSI), CASH PUBLIC ASSISTANCE INCOME, OR FOOD STAMPS/SNAP IN THE PAST 12 MONTHS',
 'RELATIONSHIP',
 'RELATIONSHIP TO HOUSEHOLDER',
 'RENT ASKED',
 'RESPONSIBILITY',
 'RESPONSIBILITY FOR OWN GRANDCHILDREN',
 'RETIREMENT INCOME IN THE PAST 12 MONTHS',
 'ROOMS',
 'SCHOOL ENROLLMENT',
 'SECOND ANCESTRY REPORTED',
 'SELECTED GROUPS',
 'SELECTED MONTHLY OWNER COSTS',
 'SELECTED MONTHLY OWNER COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS',
 'SELECTED PHYSICAL', # ???? 
 'SELECTED TRIBAL GROUPINGS',
 'SELF-CARE DIFFICULTY',
 'SELF-EMPLOYMENT INCOME IN THE PAST 12 MONTHS',
 'SERVICE-CONNECTED DISABILITY-RATING STATUS',
 'SEX',
 'SEX OF GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'SEX OF HOUSEHOLDER',
 'SEX OF PARTNER',
 'SEX OF WORKERS',
 'SHARES OF AGGREGATE HOUSEHOLD INCOME',
 'SOCIAL SECURITY INCOME',
 'SOCIAL SECURITY INCOME IN THE PAST 12 MONTHS',
 'SOME OTHER RACE ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES',
 'SPEAKS ENGLISH "VERY WELL"',
 'SPECIFIC ORIGIN',
 'SPOUSE',
 'SUBFAMILIES',
 'SUBFAMILY TYPE',
 'SUPPLEMENTAL SECURITY INCOME (SSI)',
 'SUPPLEMENTAL SECURITY INCOME (SSI) IN THE PAST 12 MONTHS',
 'TELEPHONE SERVICE AVAILABLE',
 'TENURE',
 'TENURE OF GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'TIME ARRIVING AT WORK FROM HOME',
 'TIME LEAVING HOME TO GO TO WORK',
 'TOTAL ANCESTRY REPORTED',
 "TOTAL FIELDS OF BACHELOR'S DEGREES REPORTED",
 'TOTAL POPULATION',
 'TOTAL POPULATION IN OCCUPIED HOUSING UNITS',
 'TRAVEL TIME TO WORK',
 'TRICARE/MILITARY HEALTH COVERAGE',
 'TYPE', #?????
 'TYPE OF SCHOOL',
 'TYPES OF HEALTH INSURANCE COVERAGE',
 'UNITS IN STRUCTURE',
 'UNITS IN STRUCTURE OF GRANDPARENTS LIVING WITH OWN GRANDCHILDREN UNDER 18 YEARS',
 'UNMARRIED-PARTNER HOUSEHOLDS',
 'UPPER CONTRACT RENT QUARTILE (DOLLARS)',
 'UPPER VALUE QUARTILE (DOLLARS)',
 'USUAL HOURS WORKED PER WEEK IN THE PAST 12 MONTHS',
 'VA HEALTH CARE',
 'VACANCY STATUS',
 'VACANT - CURRENT RESIDENCE ELSEWHERE',
 'VALUE',
 'VEHICLES AVAILABLE',
 'VETERAN STATUS',
 'VISION DIFFICULTY',
 'WAGE OR SALARY INCOME IN THE PAST 12 MONTHS',
 'WEEKS WORKED IN THE PAST 12 MONTHS',
 'WHITE ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES',
 'WOMEN 15 TO 50 YEARS WHO HAD A BIRTH IN THE PAST 12 MONTHS', # are this
 'WOMEN 16 TO 50 YEARS WHO HAD A BIRTH IN THE PAST 12 MONTHS', # and this meant to be the same?
 'WORK EXPERIENCE',
 'WORK EXPERIENCE IN THE PAST 12 MONTHS',
 'WORK EXPERIENCE OF HOUSEHOLDER',
 'WORK EXPERIENCE OF UNRELATED INDIVIDUALS',
 'WORK STATUS IN THE PAST 12 MONTHS',
 'WORKER POPULATION',
 'WORKERS 16 YEARS',
 "WORKERS' EARNINGS IN THE PAST 12 MONTHS (IN 2011 INFLATION-ADJUSTED DOLLARS)",
 'YEAR HOUSEHOLDER MOVED INTO UNIT',
 'YEAR OF ENTRY',
 'YEAR STRUCTURE BUILT'
]

